Update build-kernel-a13-5.15.yml

diff --git a/.github/workflows/build-kernel-a13-5.15.yml b/.github/workflows/build-kernel-a13-5.15.yml
--- a/.github/workflows/build-kernel-a13-5.15.yml
+++ b/.github/workflows/build-kernel-a13-5.15.yml
@@ -275,10 +275,14 @@ jobs:
           cd ./KernelSU
           echo "Applying SUSFS patches..."
           patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
-          
-          echo "Applying mksu_susfs.patch"
+            
+          echo "Applying MKSU specific SUSFS patch..."
           cp ../../kernel_patches/mksu_susfs.patch ../KernelSU/
           patch -p1 < mksu_susfs.patch
+        else
+          echo "Invalid KernelSU variant selected!"
+          exit 1
+        fi
 
           # Change to common directory and apply SUSFS patch
           cd ../common
@@ -322,10 +326,8 @@ jobs:
           echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
           echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig
 
-          # Add additional tmpfs config setting
-          echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./common/arch/arm64/configs/gki_defconfig
-          echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./common/arch/arm64/configs/gki_defconfig
-          echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./common/arch/arm64/configs/gki_defconfig
+          # Remove check_defconfig
+          sed -i 's/check_defconfig//' ./common/build.config.gki
 
 
       - name: Run sed and perl Commands
