Update build-kernel-a13-5.15.yml

diff --git a/.github/workflows/build-kernel-a13-5.15.yml b/.github/workflows/build-kernel-a13-5.15.yml
--- a/.github/workflows/build-kernel-a13-5.15.yml
+++ b/.github/workflows/build-kernel-a13-5.15.yml
@@ -188,6 +188,17 @@ jobs:
 
           echo "Adding KernelSU..."
           curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash $BRANCH
+          
+            # Revert commit of remove pts_unix98_lookup_pre
+            cd KernelSU
+            git revert -m 1 $(git log --grep="remove devpts hook" --pretty=format:"%h") -n
+            KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 12063)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
+          else
+            echo "Invalid KernelSU variant selected!"
+            exit 1
+          fi
 
       - name: Add KernelSU-MKSU
         if: ${{ inputs.kernelsu_variant == 'MKSU' }}
@@ -197,6 +208,17 @@ jobs:
 
           echo "Adding KernelSU..."
           curl -LSs "https://raw.githubusercontent.com/5ec1cff/KernelSU/main/kernel/setup.sh" | bash $BRANCH
+
+            # Revert commit of remove pts_unix98_lookup_pre
+            cd KernelSU
+            git revert -m 1 $(git log --grep="remove devpts hook" --pretty=format:"%h") -n
+            KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 12063)
+            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+            sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile
+          else
+            echo "Invalid KernelSU variant selected!"
+            exit 1
+          fi
           
       - name: Add KernelSU-MKSU-trilateral
         if: ${{ inputs.kernelsu_variant == 'MKSU-trilateral' }}
