Update build-kernel-a13-5.15.yml

diff --git a/.github/workflows/build-kernel-a13-5.15.yml b/.github/workflows/build-kernel-a13-5.15.yml
--- a/.github/workflows/build-kernel-a13-5.15.yml
+++ b/.github/workflows/build-kernel-a13-5.15.yml
@@ -2,6 +2,16 @@ name: Build Android 13 5.15 GKI Kernels
 
 on:
   workflow_call:  # This allows this workflow to be called from another workflow
+    inputs:
+      lto_type:
+        required: true
+        type: string
+      next_branch:
+        required: true
+        type: string
+      next_branch_other:
+        required: false
+        type: string
   
 jobs:
   build-kernel-a13-5-15-kernelsu-susfs:
@@ -11,40 +21,8 @@ jobs:
         include:
           - android_version: "android13"
             kernel_version: "5.15"
-            sub_level: "94"
-            os_patch_level: "2023-05"
-          - android_version: "android13"
-            kernel_version: "5.15"
-            sub_level: "123"
-            os_patch_level: "2023-11"
-          - android_version: "android13"
-            kernel_version: "5.15"
-            sub_level: "137"
-            os_patch_level: "2024-01"
-          - android_version: "android13"
-            kernel_version: "5.15"
-            sub_level: "144"
-            os_patch_level: "2024-03"
-          - android_version: "android13"
-            kernel_version: "5.15"
-            sub_level: "148"
-            os_patch_level: "2024-05"
-          - android_version: "android13"
-            kernel_version: "5.15"
             sub_level: "149"
             os_patch_level: "2024-07"
-          - android_version: "android13"
-            kernel_version: "5.15"
-            sub_level: "151"
-            os_patch_level: "2024-08"
-          - android_version: "android13"
-            kernel_version: "5.15"
-            sub_level: "167"
-            os_patch_level: "2024-11"
-          #- android_version: "android13"
-          #  kernel_version: "5.15"
-          #  sub_level: "X"
-          #  os_patch_level: "lts"
 
     steps:
       - name: Maximize build space
@@ -52,7 +30,7 @@ jobs:
         with:
           root-reserve-mb: 8192
           temp-reserve-mb: 2048
-          swap-size-mb: 8192
+          swap-size-mb: 20000
           remove-dotnet: 'true'
           remove-android: 'true'
           remove-haskell: 'true'
@@ -140,13 +118,26 @@ jobs:
           $REPO --version
           $REPO --trace sync -c -j$(nproc --all) --no-tags --fail-fast
 
+      - name: Determine the branch for kernelsu
+        run: |
+          if [[ "${{ inputs.next_branch }}" == "Stable" ]]; then
+            echo "BRANCH=-" >> $GITHUB_ENV
+          elif [[ "${{ inputs.next_branch }}" == "Dev" ]]; then
+            echo "BRANCH=-s next" >> $GITHUB_ENV
+          elif [[ "${{ inputs.next_branch }}" == "Other" && -n "${{ inputs.next_branch_other }}" ]]; then
+            echo "BRANCH=-s ${{ inputs.next_branch_other }}" >> $GITHUB_ENV
+          else
+            echo "Error: Custom branch not provided for 'Other'" >&2
+            exit 1
+          fi
+
       - name: Add KernelSU
         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG"
           
           echo "Adding KernelSU..."
-          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
+          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash $BRANCH
 
       - name: Apply SUSFS Patches
         run: |
@@ -156,20 +147,33 @@ jobs:
           echo "Applying SUSFS patches..."
           
           # Copy SUSFS patches
-          cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU/
+          cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
           cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}.patch ./common/
           cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
 
-          cd ./KernelSU
+          cd ./KernelSU-Next
           
           # Apply SUSFS patch for KernelSU
-          patch -p1 --forward < 10_enable_susfs_for_ksu.patch
+          patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
           
           # Change to common directory and apply SUSFS patch
           cd ../common
-          patch -p1 < 50_add_susfs_in_gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}.patch
+          patch -p1 < 50_add_susfs_in_gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}.patch || true
           
+      - name: Apply Next-SUSFS Patches
+        run: |
+          echo "Changing to configuration directory: $CONFIG..."
+          cd "$CONFIG"
+          
+          echo "Applying next SUSFS patches..."
+          cp ../kernel_patches/apk_sign.c_fix.patch ./
+          patch -p1 -F 3 < apk_sign.c_fix.patch
+          cp ../kernel_patches/core_hook.c_fix.patch ./
+          patch -p1 --fuzz=3 < core_hook.c_fix.patch
+          cp ../kernel_patches/selinux.c_fix.patch ./
+          patch -p1 -F 3 < selinux.c_fix.patch
+
       - name: Apply Hide Stuff Patches
         run: |
           echo "Changing to configuration directory: $CONFIG..."
@@ -217,7 +221,7 @@ jobs:
           # Run sed commands for modifications
           sed -i 's/check_defconfig//' ./common/build.config.gki
           sed -i 's/-dirty//' ./common/scripts/setlocalversion
-          sed -i '$s|echo "\$res5.15.149-android13-8-SUSFS"|echo "\$res-mJtUyT+"|' ./common/scripts/setlocalversion
+          sed -i '$s|echo "\$res5.15.149-android13-8-SUSFS"|echo "\$res-mJtUyT"|' ./common/scripts/setlocalversion
           
           # Run perl command to modify UTS_VERSION
           perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Sat Apr 20 04:20:00 UTC 2024"}' ./common/scripts/mkcompile_h
@@ -228,7 +232,7 @@ jobs:
           cd "$CONFIG"
           
           echo "Building the kernel..."
-          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
+          LTO=${{ inputs.lto_type }} BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
 
       - name: Create Bootimgs Folder and Copy Images
         run: |
@@ -297,3 +301,10 @@ jobs:
           path: |
             *.zip
             *.img
+
+      - name: Clear GitHub Workspace
+        if: ${{ inputs.runner == 'ubuntu-22.04-local' }}
+        run: |
+          echo "Clearing the GitHub workspace..."
+          rm -rf $GITHUB_WORKSPACE/*
+          echo "Workspace cleared."
