Update build-kernel-a13-5.15.yml

diff --git a/.github/workflows/build-kernel-a13-5.15.yml b/.github/workflows/build-kernel-a13-5.15.yml
--- a/.github/workflows/build-kernel-a13-5.15.yml
+++ b/.github/workflows/build-kernel-a13-5.15.yml
@@ -185,9 +185,6 @@ jobs:
         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG"
-        
-          pwd
-          ls -al
           
           echo "Applying SUSFS patches..."
           
@@ -217,6 +214,11 @@ jobs:
             cd ./KernelSU-Next
             cp ../../kernel_patches/next/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./
             patch -p1 --forward < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
+           
+          else
+            echo "Invalid KernelSU variant selected!"
+            exit 1
+          fi
 
           # Change to common directory and apply common SUSFS patch
           cd ../common
